name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    permissions:
        contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.2

      - name: Install Build Dependencies
        run: |
            apt-get update
            apt-get install -y make

      - name: Build
        run: RELEASE_VERSION=${{ github.ref_name }} make

      - name: Calculate and Save Checksums
        run: |
          sha256sum lilipod >> checksums.txt

      - name: Create Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --generate-notes lilipod checksums.txt

      - name: Attest Release Files
        id: attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'lilipod, checksums.txt'